.building: &building
  script:
    - $PYTHON_EXECUTABLE -m pip install .[dev]
    - $PYTHON_EXECUTABLE -m pytest

build:gcc-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3-gcc
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXECUTABLE: /usr/bin/python3

build:llvm-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3-clang
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXECUTABLE: /usr/bin/python3

build:gcc-python2:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python2-gcc
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXECUTABLE: /usr/bin/python2

build:llvm-python2:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python2-clang
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXECUTABLE: /usr/bin/python2
