image: docker.io/mdavezac/pylada-light
stages:
  - build
  - test

.building: &building
  stage: build
  script:
    - source /etc/bashrc
    - module load mpi
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=$PYTHON_EXEC ..
    - make -j 2 VERBOSE=1
  artifacts:
    paths:
      - build
    expire_in: "2 hrs"
    when: always

.testing: &testing
  stage: test
  script:
    - source /etc/bashrc
    - module load mpi
    - cd build
    - ctest -V .

build:gcc-python3:
  <<: *building
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXEC: /usr/bin/python3

build:llvm-python3:
  <<: *building
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXEC: /usr/bin/python3

test:gcc-python3:
  <<: *testing
  dependencies:
    - build:gcc-python3

test:llvm-python3:
  <<: *testing
  dependencies:
    - build:llvm-python3


build:gcc-python2:
  <<: *building
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXEC: /usr/bin/python2

build:llvm-python2:
  <<: *building
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXEC: /usr/bin/python2

test:gcc-python2:
  <<: *testing
  dependencies:
    - build:gcc-python2

test:llvm-python2:
  <<: *testing
  dependencies:
    - build:llvm-python2
