.building: &building
  script:
    - source /etc/bashrc
    - module load mpi
    - $PYTHON_EXECUTABLE -m pip install -e .[dev]
    - $PYTHON_EXECUTABLE -m pip install pytest
    - $PYTHON_EXECUTABLE -m pytest

build:gcc-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXECUTABLE: /usr/bin/python3

build:llvm-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXECUTABLE: /usr/bin/python3
