stages:
  - build
  - test

.building: &building
  stage: build
  script:
    - source /etc/bashrc
    - module load mpi
    - $PYTHON_EXECUTABLE -m pip install -e .[dev]
  artifacts:
    paths:
      - build
    expire_in: "2 hrs"
    when: always

.testing: &testing
  stage: test
  script:
    - source /etc/bashrc
    - module load mpi
    - pip install pytest
    - $PYTHON_EXECUTABLE -m pytest

build:gcc-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  variables:
    CC: gcc
    CXX: g++
    PYTHON_EXECUTABLE: /usr/bin/python3

build:llvm-python3:
  <<: *building
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  variables:
    CC: clang
    CXX: clang++
    PYTHON_EXECUTABLE: /usr/bin/python3

test:gcc-python3:
  <<: *testing
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  dependencies:
    - build:gcc-python3
  variables:
    PYTHON_EXECUTABLE: /usr/bin/python3

test:llvm-python3:
  <<: *testing
  image: registry.gitlab.com/mdavezac/pylada-light:python3
  dependencies:
    - build:llvm-python3
  variables:
    PYTHON_EXECUTABLE: /usr/bin/python3
