strategy:
    imageName: macos-10.13
    pythonVersion: 3.7

pool:
  vmImage: $(imageName)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true

  - script: |
      apt install fortran
    name: gfort2
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      brew install gcc
    name: gfort1
    condition: ne(variables['Agent.OS'], 'Linux')

  - script: |
      python3 -m pip  install .[dev]
    name: setup

  - script: |
      python3 -m pip install pytest-cov
      python3 -m pip pytest --junitxml=junit/pytest.xml \
          --cov=src/muse \
          --cov-report=xml:coverage/coverage.xml \
          --cov-report=html:coverage
    name: test_with_coverage

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: junit/*.xml
      testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)]'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage/coverage.xml
      reportDirectory: coverage
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Linux'))
