pool:
  vmImage: macos-10.13

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: x64

  - script: |
      apt install fortran
    name: test
    condition: ne(variables['Agent.OS'], 'Linux')

  - script: |
      brew install gcc
    name: test
    condition: ne(variables['Agent.OS'], 'Linux')

  - script: |
      pip install -e.[dev]
    name: setup

  - script: |
      pip install pytest-cov
      pytest --junitxml=junit/pytest.xml \
          --cov=src/muse \
          --cov-report=xml:coverage/coverage.xml \
          --cov-report=html:coverage
    name: test_with_coverage
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      pytest --junitxml=junit/pytest.xml
    name: test
    condition: ne(variables['Agent.OS'], 'Linux')

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: junit/*.xml
      testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)]'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage/coverage.xml
      reportDirectory: coverage
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Linux'))
